# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_density_function <- function(m1, N) {
    .Call('snowboot_get_density_function', PACKAGE = 'snowboot', m1, N)
}

